/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aula_4.pkg01_09_2025;

import javax.swing.JOptionPane;

/**
 *
 * @author 2830482411021
 */
public class Form2 extends javax.swing.JFrame {

    /**
     * Creates new form Form2
     */
    String nome;
    char sexo;
    boolean tecnologia, esportes, astronomia;
    
    public Form2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Sexo = new javax.swing.ButtonGroup();
        lbl_nome = new javax.swing.JLabel();
        txf_nome = new javax.swing.JTextField();
        rdo_sexoMasc = new javax.swing.JRadioButton();
        rdo_sexoFem = new javax.swing.JRadioButton();
        lbl_sexo = new javax.swing.JLabel();
        btn_save = new javax.swing.JButton();
        chk_Tecnologia = new javax.swing.JCheckBox();
        chk_Astronomia = new javax.swing.JCheckBox();
        chk_Esportes = new javax.swing.JCheckBox();
        lbl_interesse = new javax.swing.JLabel();
        lbl_idioma = new javax.swing.JLabel();
        cmb_Idioma = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_nome.setText("Nome:");

        Sexo.add(rdo_sexoMasc);
        rdo_sexoMasc.setText("Masculino");
        rdo_sexoMasc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdo_sexoMascActionPerformed(evt);
            }
        });

        Sexo.add(rdo_sexoFem);
        rdo_sexoFem.setText("Feminino");

        lbl_sexo.setText("Sexo:");

        btn_save.setText("Salvar");
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });

        chk_Tecnologia.setText("Tecnologia");
        chk_Tecnologia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk_TecnologiaActionPerformed(evt);
            }
        });

        chk_Astronomia.setText("Astronomia");
        chk_Astronomia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk_AstronomiaActionPerformed(evt);
            }
        });

        chk_Esportes.setText("Esportes");
        chk_Esportes.setToolTipText("");
        chk_Esportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk_EsportesActionPerformed(evt);
            }
        });

        lbl_interesse.setText("Interesses: ");

        lbl_idioma.setText("Idioma: ");

        cmb_Idioma.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Português", "Inglês", "Alemão", "Francês", "Mandarim", "Espanhol", "Aramaico", "Hungaro" }));
        cmb_Idioma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_IdiomaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_save)
                .addGap(52, 52, 52))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lbl_nome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_sexo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(lbl_interesse)
                    .addComponent(lbl_idioma))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmb_Idioma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(chk_Tecnologia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chk_Astronomia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chk_Esportes))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(rdo_sexoMasc)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(rdo_sexoFem))
                        .addComponent(txf_nome)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_nome)
                    .addComponent(txf_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdo_sexoMasc)
                    .addComponent(rdo_sexoFem)
                    .addComponent(lbl_sexo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chk_Tecnologia)
                    .addComponent(chk_Astronomia)
                    .addComponent(chk_Esportes)
                    .addComponent(lbl_interesse))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_idioma)
                    .addComponent(cmb_Idioma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(btn_save)
                .addContainerGap(106, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdo_sexoMascActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdo_sexoMascActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdo_sexoMascActionPerformed

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
        esportes = chk_Esportes.isSelected();
        astronomia = chk_Astronomia.isSelected();
        tecnologia = chk_Tecnologia.isSelected();
        
        if(rdo_sexoMasc.isSelected()){
            sexo = 'M';
            JOptionPane.showMessageDialog(null,"Sexo selecionado: "+sexo, "Alerta!", JOptionPane.OK_OPTION);
        } else if(rdo_sexoFem.isSelected()){
            sexo = 'F';
            JOptionPane.showMessageDialog(null, "Sexo selecionado: "+sexo, "Alerta!", JOptionPane.OK_OPTION);
        } else{
            JOptionPane.showMessageDialog(null, "Selecione um sexo", "Erro!", JOptionPane.ERROR_MESSAGE);
        }
        
        JOptionPane.showMessageDialog(null, "Tecnologia: "+tecnologia+"\nAstronomia: "+astronomia+
                "\nEsportes: "+esportes, "Alerta", JOptionPane.INFORMATION_MESSAGE);
        
        JOptionPane.showMessageDialog(null, "Idioma selecionado: "+cmb_Idioma.getSelectedItem(), "Alerta", JOptionPane.INFORMATION_MESSAGE);
        
        JOptionPane.showMessageDialog(null, "Sexo: ");
        
        
        
        
        
    }//GEN-LAST:event_btn_saveActionPerformed

    private void chk_TecnologiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk_TecnologiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chk_TecnologiaActionPerformed

    private void chk_AstronomiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk_AstronomiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chk_AstronomiaActionPerformed

    private void chk_EsportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk_EsportesActionPerformed
        
    }//GEN-LAST:event_chk_EsportesActionPerformed

    private void cmb_IdiomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_IdiomaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_IdiomaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Sexo;
    private javax.swing.JButton btn_save;
    private javax.swing.JCheckBox chk_Astronomia;
    private javax.swing.JCheckBox chk_Esportes;
    private javax.swing.JCheckBox chk_Tecnologia;
    private javax.swing.JComboBox<String> cmb_Idioma;
    private javax.swing.JLabel lbl_idioma;
    private javax.swing.JLabel lbl_interesse;
    private javax.swing.JLabel lbl_nome;
    private javax.swing.JLabel lbl_sexo;
    private javax.swing.JRadioButton rdo_sexoFem;
    private javax.swing.JRadioButton rdo_sexoMasc;
    private javax.swing.JTextField txf_nome;
    // End of variables declaration//GEN-END:variables
}
