/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Cliente;

import DAO.ClienteDAO;
import javax.swing.JOptionPane;

/**
 *
 * @author fan25
 */
public class ClienteCadastrar extends javax.swing.JFrame {

    /**
     * Creates new form ClienteCadastrar
     */
    public ClienteCadastrar() {
        initComponents();
    }
    
    public void limparFormulario(){
        txt_nome.setText("");
        txt_cpf.setText("");
        txt_cnpj.setText("");
        txt_email.setText("");
        txt_telefone.setText("");
        txt_logradouro.setText("");
        txt_bairro.setText("");
        txt_municipio.setText("");
        cmb_uf.setSelectedIndex(0);
        TipoCliente.clearSelection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TipoCliente = new javax.swing.ButtonGroup();
        lbl_cadastro = new javax.swing.JLabel();
        lbl_nome = new javax.swing.JLabel();
        txt_nome = new javax.swing.JTextField();
        lbl_cpf = new javax.swing.JLabel();
        lbl_email = new javax.swing.JLabel();
        txt_cpf = new javax.swing.JFormattedTextField();
        txt_email = new javax.swing.JTextField();
        lbl_email1 = new javax.swing.JLabel();
        txt_telefone = new javax.swing.JFormattedTextField();
        lbl_logradouro = new javax.swing.JLabel();
        lbl_dados = new javax.swing.JLabel();
        lbl_Endereco = new javax.swing.JLabel();
        txt_logradouro = new javax.swing.JTextField();
        lbl_bairro = new javax.swing.JLabel();
        txt_bairro = new javax.swing.JTextField();
        lbl_municipio = new javax.swing.JLabel();
        txt_municipio = new javax.swing.JTextField();
        lbl_uf = new javax.swing.JLabel();
        cmb_uf = new javax.swing.JComboBox<>();
        rdo_fisica = new javax.swing.JRadioButton();
        rdo_juridica = new javax.swing.JRadioButton();
        lbl_tipoCliente = new javax.swing.JLabel();
        btn_cadastrar = new javax.swing.JButton();
        btn_limpar = new javax.swing.JButton();
        btn_listarClientes = new javax.swing.JButton();
        lbl_cnpj = new javax.swing.JLabel();
        lbl_ou = new javax.swing.JLabel();
        txt_cnpj = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lbl_cadastro.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lbl_cadastro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_cadastro.setText("Cadastro de Clientes");

        lbl_nome.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbl_nome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_nome.setText("Nome:");

        txt_nome.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txt_nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nomeActionPerformed(evt);
            }
        });

        lbl_cpf.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbl_cpf.setText("CPF: ");

        lbl_email.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbl_email.setText("Email: ");

        try {
            txt_cpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txt_cpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cpfActionPerformed(evt);
            }
        });

        txt_email.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txt_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_emailActionPerformed(evt);
            }
        });

        lbl_email1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbl_email1.setText("Telefone: ");

        try {
            txt_telefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ######-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txt_telefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_telefoneActionPerformed(evt);
            }
        });

        lbl_logradouro.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbl_logradouro.setText("Logradouro: ");

        lbl_dados.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbl_dados.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_dados.setText("<-----Dados----->");

        lbl_Endereco.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbl_Endereco.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Endereco.setText("<-----Endereço----->");

        txt_logradouro.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txt_logradouro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_logradouroActionPerformed(evt);
            }
        });

        lbl_bairro.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbl_bairro.setText("Bairro: ");

        txt_bairro.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txt_bairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_bairroActionPerformed(evt);
            }
        });

        lbl_municipio.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbl_municipio.setText("Municipio: ");

        txt_municipio.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txt_municipio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_municipioActionPerformed(evt);
            }
        });

        lbl_uf.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbl_uf.setText("UF: ");

        cmb_uf.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cmb_uf.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));

        TipoCliente.add(rdo_fisica);
        rdo_fisica.setText("Pessoa Física");
        rdo_fisica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdo_fisicaActionPerformed(evt);
            }
        });

        TipoCliente.add(rdo_juridica);
        rdo_juridica.setText("Pessoa Júridica");

        lbl_tipoCliente.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbl_tipoCliente.setText("Tipo: ");

        btn_cadastrar.setText("Cadastrar");
        btn_cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadastrarActionPerformed(evt);
            }
        });

        btn_limpar.setText("Limpar");
        btn_limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limparActionPerformed(evt);
            }
        });

        btn_listarClientes.setText("Listar Clientes");
        btn_listarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_listarClientesActionPerformed(evt);
            }
        });

        lbl_cnpj.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbl_cnpj.setText("CNPJ: ");

        lbl_ou.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbl_ou.setText("OU ");

        try {
            txt_cnpj.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txt_cnpj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cnpjActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_email1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_telefone))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_nome)
                                    .addComponent(lbl_cpf))
                                .addGap(5, 5, 5)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_nome)
                                    .addComponent(txt_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_cnpj)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_cnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_email)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_email)))
                        .addGap(53, 53, 53))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lbl_cadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lbl_dados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(lbl_ou)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(btn_listarClientes))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lbl_bairro)
                            .addGap(49, 49, 49)
                            .addComponent(txt_bairro))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lbl_logradouro)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txt_logradouro))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbl_municipio)
                                .addComponent(lbl_uf)
                                .addComponent(lbl_tipoCliente)
                                .addComponent(btn_limpar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(14, 14, 14)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt_municipio)
                                .addComponent(cmb_uf, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(rdo_fisica)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btn_cadastrar)
                                        .addComponent(rdo_juridica))
                                    .addGap(0, 4, Short.MAX_VALUE)))))
                    .addComponent(lbl_Endereco, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_cadastro)
                .addGap(16, 16, 16)
                .addComponent(lbl_dados)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_nome)
                    .addComponent(txt_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_cpf)
                    .addComponent(txt_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_ou)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_cnpj)
                    .addComponent(txt_cnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_email)
                    .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_email1)
                    .addComponent(txt_telefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lbl_Endereco)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_logradouro)
                    .addComponent(txt_logradouro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_bairro)
                    .addComponent(txt_bairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_municipio)
                    .addComponent(txt_municipio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_uf)
                    .addComponent(cmb_uf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdo_fisica)
                    .addComponent(rdo_juridica)
                    .addComponent(lbl_tipoCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_limpar)
                    .addComponent(btn_cadastrar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_listarClientes)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nomeActionPerformed

    private void txt_cpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cpfActionPerformed

    private void txt_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_emailActionPerformed

    private void txt_telefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_telefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_telefoneActionPerformed

    private void txt_logradouroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_logradouroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_logradouroActionPerformed

    private void txt_bairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_bairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_bairroActionPerformed

    private void txt_municipioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_municipioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_municipioActionPerformed

    private void rdo_fisicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdo_fisicaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdo_fisicaActionPerformed

    private void btn_cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastrarActionPerformed
        int tipo = -1;
        
        if(rdo_fisica.isSelected()){
            tipo = 1;
        } else if(rdo_juridica.isSelected()){
            tipo = 2;
        }
        
        if(tipo == -1){
            JOptionPane.showMessageDialog(null, "É necessario definir o tipo de Cliente a ser Inserido!!", "Tipo de Cliente Não Selecionado!", JOptionPane.OK_OPTION);
        } else if(!txt_cpf.getText().equals("   .   .   -  ") && tipo == 2 || !txt_cnpj.getText().equals("  .   .   /    -  ") && tipo == 1 || txt_cpf.getText().equals("   .   .   -  ") && txt_cnpj.getText().equals("  .   .   /    -  ")){
            JOptionPane.showMessageDialog(
                    null,
                    "É necessário inserir o documento respectivo ao tipo de usuario desejado!"
                    + "\n  -Se for 'Pessoa Física', insira um 'CPF'"
                    + "\n  -Se for 'Pessoa Júridica', insira um 'CNPJ'", 
                    "Tipo de Cliente Não é Compativel com o Documento!",
                    JOptionPane.OK_OPTION
            );
        } else{
            //Passagem dos valores para o objeto 'cliente'
            Cliente cliente = new Cliente();
            cliente.setNome(txt_nome.getText());
            if(txt_cpf.getText().equals("   .   .   -  ")){
                cliente.setDocumento(txt_cnpj.getText());
            } else{
                cliente.setDocumento(txt_cpf.getText());
            }
            
            cliente.setEmail(txt_email.getText());
            cliente.setTelefone(txt_telefone.getText());
            cliente.setLogradouro(txt_logradouro.getText());
            cliente.setBairro(txt_bairro.getText());
            cliente.setMunicipio(txt_municipio.getText());
            cliente.setUf(cmb_uf.getSelectedItem().toString());
            cliente.setCodigoTipo(tipo);

            //Passando o Objeto 'cliente' como parametro para a persistencia com o banco de dados
            ClienteDAO clienteDAO = new ClienteDAO();
            clienteDAO.cadastrar(cliente);

            limparFormulario();
        }
    }//GEN-LAST:event_btn_cadastrarActionPerformed

    private void btn_limparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limparActionPerformed
        limparFormulario();
    }//GEN-LAST:event_btn_limparActionPerformed

    private void btn_listarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_listarClientesActionPerformed
        ClienteListar listClientes = new ClienteListar();
        listClientes.setVisible(true);

    }//GEN-LAST:event_btn_listarClientesActionPerformed

    private void txt_cnpjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cnpjActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cnpjActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClienteCadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClienteCadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClienteCadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClienteCadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClienteCadastrar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup TipoCliente;
    private javax.swing.JButton btn_cadastrar;
    private javax.swing.JButton btn_limpar;
    private javax.swing.JButton btn_listarClientes;
    private javax.swing.JComboBox<String> cmb_uf;
    private javax.swing.JLabel lbl_Endereco;
    private javax.swing.JLabel lbl_bairro;
    private javax.swing.JLabel lbl_cadastro;
    private javax.swing.JLabel lbl_cnpj;
    private javax.swing.JLabel lbl_cpf;
    private javax.swing.JLabel lbl_dados;
    private javax.swing.JLabel lbl_email;
    private javax.swing.JLabel lbl_email1;
    private javax.swing.JLabel lbl_logradouro;
    private javax.swing.JLabel lbl_municipio;
    private javax.swing.JLabel lbl_nome;
    private javax.swing.JLabel lbl_ou;
    private javax.swing.JLabel lbl_tipoCliente;
    private javax.swing.JLabel lbl_uf;
    private javax.swing.JRadioButton rdo_fisica;
    private javax.swing.JRadioButton rdo_juridica;
    private javax.swing.JTextField txt_bairro;
    private javax.swing.JFormattedTextField txt_cnpj;
    private javax.swing.JFormattedTextField txt_cpf;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_logradouro;
    private javax.swing.JTextField txt_municipio;
    private javax.swing.JTextField txt_nome;
    private javax.swing.JFormattedTextField txt_telefone;
    // End of variables declaration//GEN-END:variables
}
