
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author fan25
 */
public class CRUD extends javax.swing.JFrame {

    /**
     * Creates new form CRUD
     */
    public CRUD() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Sexo_aluno = new javax.swing.ButtonGroup();
        Sexo_aluno2 = new javax.swing.ButtonGroup();
        sexo_professor = new javax.swing.ButtonGroup();
        sexo_professor2 = new javax.swing.ButtonGroup();
        lbl_form2_aluno = new javax.swing.JLabel();
        btn_excluir_aluno = new javax.swing.JButton();
        txt_RA_aluno = new javax.swing.JTextField();
        rdo_masculino2_aluno = new javax.swing.JRadioButton();
        lbl_id = new javax.swing.JLabel();
        rdo_feminino2_aluno = new javax.swing.JRadioButton();
        btn_consultar_aluno = new javax.swing.JButton();
        cmb_idioma_aluno2 = new javax.swing.JComboBox<>();
        lbl_sexo2_aluno = new javax.swing.JLabel();
        lbl_idioma2_aluno = new javax.swing.JLabel();
        btn_atualizar_aluno = new javax.swing.JButton();
        txt_ra_aluno = new javax.swing.JTextField();
        lbl_ra_aluno = new javax.swing.JLabel();
        lbl_sexo_aluno = new javax.swing.JLabel();
        lbl_idioma_aluno = new javax.swing.JLabel();
        rdo_masculino_aluno = new javax.swing.JRadioButton();
        rdo_feminino_aluno = new javax.swing.JRadioButton();
        cmb_idioma_aluno = new javax.swing.JComboBox<>();
        btn_salvar_aluno = new javax.swing.JButton();
        txt_RA_aluno2 = new javax.swing.JTextField();
        lbl_form1_aluno = new javax.swing.JLabel();
        lbl_id2_aluno = new javax.swing.JLabel();
        btn_consultar_professor = new javax.swing.JButton();
        cmb_idioma_professor2 = new javax.swing.JComboBox<>();
        txt_Nome_professor = new javax.swing.JTextField();
        lbl_nome2_professor = new javax.swing.JLabel();
        lbl_sexo2_professor = new javax.swing.JLabel();
        lbl_idioma2_professor = new javax.swing.JLabel();
        btn_atualizar_professor = new javax.swing.JButton();
        txt_nome_professor = new javax.swing.JTextField();
        lbl_nome_professor = new javax.swing.JLabel();
        lbl_sexo_professor = new javax.swing.JLabel();
        lbl_idioma_professor = new javax.swing.JLabel();
        rdo_masculino_professor = new javax.swing.JRadioButton();
        rdo_feminino_professor = new javax.swing.JRadioButton();
        cmb_idioma_professor = new javax.swing.JComboBox<>();
        btn_salvar_professor = new javax.swing.JButton();
        txt_ID_professor = new javax.swing.JTextField();
        lbl_form2_professor = new javax.swing.JLabel();
        btn_excluir_professor = new javax.swing.JButton();
        lbl_form1_professor = new javax.swing.JLabel();
        lbl_id2_professor = new javax.swing.JLabel();
        txt_id_professor = new javax.swing.JTextField();
        rdo_masculino2_professor = new javax.swing.JRadioButton();
        lbl_id_professor = new javax.swing.JLabel();
        rdo_feminino2_professor = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        txt_media_aluno = new javax.swing.JTextField();
        lbl_media_aluno = new javax.swing.JLabel();
        txt_faltas_aluno = new javax.swing.JTextField();
        lbl_faltas_aluno = new javax.swing.JLabel();
        txt_media_aluno2 = new javax.swing.JTextField();
        lbl_media_aluno1 = new javax.swing.JLabel();
        txt_faltas_aluno2 = new javax.swing.JTextField();
        lbl_faltas_aluno1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_form2_aluno.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lbl_form2_aluno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_form2_aluno.setText("EDITAR E EXCLUIR PESSOA (ALUNO)");

        btn_excluir_aluno.setText("Excluir");
        btn_excluir_aluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_excluir_alunoActionPerformed(evt);
            }
        });

        txt_RA_aluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_RA_alunoActionPerformed(evt);
            }
        });

        Sexo_aluno2.add(rdo_masculino2_aluno);
        rdo_masculino2_aluno.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rdo_masculino2_aluno.setText("Masculino");
        rdo_masculino2_aluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdo_masculino2_alunoActionPerformed(evt);
            }
        });

        lbl_id.setText("RA: ");

        Sexo_aluno2.add(rdo_feminino2_aluno);
        rdo_feminino2_aluno.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rdo_feminino2_aluno.setText("Feminino");
        rdo_feminino2_aluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdo_feminino2_alunoActionPerformed(evt);
            }
        });

        btn_consultar_aluno.setText("Consultar");
        btn_consultar_aluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_consultar_alunoActionPerformed(evt);
            }
        });

        cmb_idioma_aluno2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Português", "Inglês", "Mandarim", "Aramaico", "Francês", "Espanhol", "Alemão" }));

        lbl_sexo2_aluno.setText("Sexo: ");

        lbl_idioma2_aluno.setText("Idioma:");

        btn_atualizar_aluno.setText("Atualizar");
        btn_atualizar_aluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_atualizar_alunoActionPerformed(evt);
            }
        });

        txt_ra_aluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ra_alunoActionPerformed(evt);
            }
        });

        lbl_ra_aluno.setText("RA:");

        lbl_sexo_aluno.setText("Sexo:");

        lbl_idioma_aluno.setText("Idioma: ");

        Sexo_aluno.add(rdo_masculino_aluno);
        rdo_masculino_aluno.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rdo_masculino_aluno.setText("Masculino");
        rdo_masculino_aluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdo_masculino_alunoActionPerformed(evt);
            }
        });

        Sexo_aluno.add(rdo_feminino_aluno);
        rdo_feminino_aluno.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rdo_feminino_aluno.setText("Feminino");
        rdo_feminino_aluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdo_feminino_alunoActionPerformed(evt);
            }
        });

        cmb_idioma_aluno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Português", "Inglês", "Mandarim", "Aramaico", "Francês", "Espanhol", "Alemão" }));

        btn_salvar_aluno.setText("Salvar");
        btn_salvar_aluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salvar_alunoActionPerformed(evt);
            }
        });

        txt_RA_aluno2.setEditable(false);
        txt_RA_aluno2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_RA_aluno2ActionPerformed(evt);
            }
        });

        lbl_form1_aluno.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lbl_form1_aluno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_form1_aluno.setText("ALUNO");

        lbl_id2_aluno.setText("RA: ");

        btn_consultar_professor.setText("Consultar");
        btn_consultar_professor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_consultar_professorActionPerformed(evt);
            }
        });

        cmb_idioma_professor2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Português", "Inglês", "Mandarim", "Aramaico", "Francês", "Espanhol", "Alemão" }));

        txt_Nome_professor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Nome_professorActionPerformed(evt);
            }
        });

        lbl_nome2_professor.setText("Nome:");

        lbl_sexo2_professor.setText("Sexo: ");

        lbl_idioma2_professor.setText("Idioma:");

        btn_atualizar_professor.setText("Atualizar");
        btn_atualizar_professor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_atualizar_professorActionPerformed(evt);
            }
        });

        txt_nome_professor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nome_professorActionPerformed(evt);
            }
        });

        lbl_nome_professor.setText("Nome:");

        lbl_sexo_professor.setText("Sexo:");

        lbl_idioma_professor.setText("Idioma: ");

        sexo_professor.add(rdo_masculino_professor);
        rdo_masculino_professor.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rdo_masculino_professor.setText("Masculino");
        rdo_masculino_professor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdo_masculino_professorActionPerformed(evt);
            }
        });

        sexo_professor.add(rdo_feminino_professor);
        rdo_feminino_professor.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rdo_feminino_professor.setText("Feminino");
        rdo_feminino_professor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdo_feminino_professorActionPerformed(evt);
            }
        });

        cmb_idioma_professor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Português", "Inglês", "Mandarim", "Aramaico", "Francês", "Espanhol", "Alemão" }));

        btn_salvar_professor.setText("Salvar");
        btn_salvar_professor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salvar_professorActionPerformed(evt);
            }
        });

        txt_ID_professor.setEditable(false);
        txt_ID_professor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ID_professorActionPerformed(evt);
            }
        });

        lbl_form2_professor.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lbl_form2_professor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_form2_professor.setText("EDITAR E EXCLUIR PESSOA (PROFESSOR)");

        btn_excluir_professor.setText("Excluir");
        btn_excluir_professor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_excluir_professorActionPerformed(evt);
            }
        });

        lbl_form1_professor.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lbl_form1_professor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_form1_professor.setText("PROFESSOR");

        lbl_id2_professor.setText("ID: ");

        txt_id_professor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_id_professorActionPerformed(evt);
            }
        });

        sexo_professor2.add(rdo_masculino2_professor);
        rdo_masculino2_professor.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rdo_masculino2_professor.setText("Masculino");
        rdo_masculino2_professor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdo_masculino2_professorActionPerformed(evt);
            }
        });

        lbl_id_professor.setText("ID: ");

        sexo_professor2.add(rdo_feminino2_professor);
        rdo_feminino2_professor.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rdo_feminino2_professor.setText("Feminino");
        rdo_feminino2_professor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdo_feminino2_professorActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("______________________________________________________________");

        txt_media_aluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_media_alunoActionPerformed(evt);
            }
        });

        lbl_media_aluno.setText("Média:");

        txt_faltas_aluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_faltas_alunoActionPerformed(evt);
            }
        });

        lbl_faltas_aluno.setText("Faltas:");

        txt_media_aluno2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_media_aluno2ActionPerformed(evt);
            }
        });

        lbl_media_aluno1.setText("Média:");

        txt_faltas_aluno2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_faltas_aluno2ActionPerformed(evt);
            }
        });

        lbl_faltas_aluno1.setText("Faltas:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_sexo_aluno)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_salvar_aluno)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rdo_masculino_aluno)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rdo_feminino_aluno))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_idioma_aluno)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmb_idioma_aluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbl_form1_aluno, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lbl_faltas_aluno)
                            .addGap(18, 18, 18)
                            .addComponent(txt_faltas_aluno, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbl_media_aluno)
                                .addComponent(lbl_ra_aluno))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt_ra_aluno, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_media_aluno, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_form2_aluno, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rdo_masculino2_aluno)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(rdo_feminino2_aluno))
                                    .addComponent(cmb_idioma_aluno2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(48, 48, 48))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btn_excluir_aluno)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn_atualizar_aluno))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbl_faltas_aluno1)
                                        .addGap(18, 18, 18)
                                        .addComponent(txt_faltas_aluno2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(lbl_media_aluno1)
                                        .addGap(18, 18, 18)
                                        .addComponent(txt_media_aluno2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lbl_id2_aluno)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txt_RA_aluno2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(60, 60, 60))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lbl_id)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txt_RA_aluno, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btn_consultar_aluno))
                                .addComponent(lbl_sexo2_aluno)
                                .addComponent(lbl_idioma2_aluno)))
                        .addGap(84, 84, 84)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl_sexo_professor)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btn_salvar_professor)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lbl_nome_professor)
                            .addGap(28, 28, 28)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(rdo_masculino_professor)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(rdo_feminino_professor))
                                .addComponent(txt_nome_professor, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_idioma_professor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmb_idioma_professor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbl_form1_professor, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_form2_professor)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_excluir_professor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_atualizar_professor))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lbl_idioma2_professor)
                                        .addComponent(lbl_sexo2_professor)
                                        .addComponent(lbl_nome2_professor))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txt_Nome_professor, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(rdo_masculino2_professor)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(rdo_feminino2_professor))
                                        .addComponent(cmb_idioma_professor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lbl_id2_professor)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txt_ID_professor, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(60, 60, 60))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lbl_id_professor)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txt_id_professor, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btn_consultar_professor))))
                        .addGap(161, 161, 161))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(0, 89, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_form1_aluno)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_ra_aluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_ra_aluno))
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_media_aluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_media_aluno))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_faltas_aluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_faltas_aluno))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_sexo_aluno)
                            .addComponent(rdo_feminino_aluno)
                            .addComponent(rdo_masculino_aluno))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmb_idioma_aluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_idioma_aluno))
                        .addGap(10, 10, 10)
                        .addComponent(btn_salvar_aluno)
                        .addGap(100, 100, 100))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_form2_aluno)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_RA_aluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_id)
                            .addComponent(btn_consultar_aluno))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_RA_aluno2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_id2_aluno))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_media_aluno2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_media_aluno1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_faltas_aluno2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_faltas_aluno1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rdo_feminino2_aluno)
                            .addComponent(rdo_masculino2_aluno)
                            .addComponent(lbl_sexo2_aluno))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_idioma2_aluno)
                            .addComponent(cmb_idioma_aluno2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_atualizar_aluno)
                            .addComponent(btn_excluir_aluno))
                        .addGap(53, 53, 53)))
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_form1_professor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_nome_professor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_nome_professor))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_sexo_professor)
                            .addComponent(rdo_feminino_professor)
                            .addComponent(rdo_masculino_professor))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_idioma_professor)
                            .addComponent(cmb_idioma_professor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btn_salvar_professor))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_form2_professor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_id_professor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_id_professor)
                            .addComponent(btn_consultar_professor))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_ID_professor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_id2_professor))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_Nome_professor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_nome2_professor))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(rdo_feminino2_professor)
                                .addComponent(rdo_masculino2_professor))
                            .addComponent(lbl_sexo2_professor))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_idioma2_professor)
                            .addComponent(cmb_idioma_professor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_atualizar_professor)
                            .addComponent(btn_excluir_professor))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_excluir_alunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_excluir_alunoActionPerformed
        int resposta = JOptionPane.showConfirmDialog(null, "Deseja realmente excluir?", "Exclusão", JOptionPane.YES_NO_OPTION);

        if(resposta == JOptionPane.YES_NO_OPTION){
            AlunoDAO aDAO = new AlunoDAO();
            aDAO.excluir(Integer.parseInt(txt_RA_aluno2.getText()));
            limparFormularioAluno2();
        }
    }//GEN-LAST:event_btn_excluir_alunoActionPerformed

    private void txt_RA_alunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_RA_alunoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_RA_alunoActionPerformed

    private void rdo_masculino2_alunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdo_masculino2_alunoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdo_masculino2_alunoActionPerformed

    private void rdo_feminino2_alunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdo_feminino2_alunoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdo_feminino2_alunoActionPerformed

    private void btn_consultar_alunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_consultar_alunoActionPerformed
        int raAluno = Integer.parseInt(txt_RA_aluno.getText());
        AlunoDAO aDAO = new AlunoDAO();

        Aluno a = aDAO.getAluno(raAluno);

        if(a == null){
            limparFormularioAluno2();
            JOptionPane.showMessageDialog(this, "Pessoa não encontrada!");
        } else{
            txt_RA_aluno2.setText(String.valueOf(a.getRa()));
            txt_media_aluno2.setText(String.valueOf(a.getMedia()));
            txt_faltas_aluno2.setText(String.valueOf(a.getFaltas()));
            if(a.getSexo().equals("M")){
                rdo_masculino2_aluno.setSelected(true);
            } else{
                rdo_feminino2_aluno.setSelected(true);
            }
            //txt_idioma.setText(p.getIdioma());
            cmb_idioma_aluno2.setSelectedItem(p.getIdioma());
        }

    }//GEN-LAST:event_btn_consultar_alunoActionPerformed

    private void btn_atualizar_alunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_atualizar_alunoActionPerformed
        String sexo = null;

        if(rdo_masculino2_aluno.isSelected()){
            sexo = "M";
        } else if(rdo_feminino2_aluno.isSelected()){
            sexo = "F";
        }

        Aluno a = new Aluno();
        a.setRa(Integer.parseInt(txt_RA_aluno.getText()));
        //a.setNome(txt_Media_aluno.getText());
        //a.setSexo(sexo);
        a.setIdioma(cmb_idioma_aluno2.getSelectedItem().toString());

        AlunoDAO aDAO = new AlunoDAO();
        //aDAO.editar(a);
        limparFormularioAluno2();
    }//GEN-LAST:event_btn_atualizar_alunoActionPerformed

    private void txt_ra_alunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ra_alunoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ra_alunoActionPerformed

    private void rdo_masculino_alunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdo_masculino_alunoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdo_masculino_alunoActionPerformed

    private void rdo_feminino_alunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdo_feminino_alunoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdo_feminino_alunoActionPerformed

    private void btn_salvar_alunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salvar_alunoActionPerformed
        String sexo = null;

        if(rdo_masculino_aluno.isSelected()){
            sexo = "M";
            /*JOptionPane.showMessageDialog(null, "Sexo selecionado: "+ sexo, "Alerta!", JOptionPane.OK_OPTION);
            */
        } else if(rdo_feminino_aluno.isSelected()){
            sexo = "F";
            /*JOptionPane.showMessageDialog(null, "Sexo selecionado: "+ sexo, "Alerta!", JOptionPane.OK_OPTION);
            */
        }

        /*if(txt_nome.getText().equals("")){

        }*/
        Aluno a = new Aluno();
        a.setRa(Integer.parseInt(txt_ra_aluno.getText()));
        a.setMedia(Float.parseFloat(txt_media_aluno.getText()));
        a.setFaltas(Integer.parseInt(txt_faltas_aluno.getText()));
        a.setSexo(sexo);
        a.setIdioma(cmb_idioma_aluno.getSelectedItem().toString());

        AlunoDAO aDAO = new AlunoDAO();
        aDAO.inserir(a);
        limparFormularioAluno();

    }//GEN-LAST:event_btn_salvar_alunoActionPerformed

    private void txt_RA_aluno2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_RA_aluno2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_RA_aluno2ActionPerformed

    private void btn_consultar_professorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_consultar_professorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_consultar_professorActionPerformed

    private void txt_Nome_professorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Nome_professorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Nome_professorActionPerformed

    private void btn_atualizar_professorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_atualizar_professorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_atualizar_professorActionPerformed

    private void txt_nome_professorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nome_professorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nome_professorActionPerformed

    private void rdo_masculino_professorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdo_masculino_professorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdo_masculino_professorActionPerformed

    private void rdo_feminino_professorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdo_feminino_professorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdo_feminino_professorActionPerformed

    private void btn_salvar_professorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salvar_professorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_salvar_professorActionPerformed

    private void txt_ID_professorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ID_professorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ID_professorActionPerformed

    private void btn_excluir_professorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_excluir_professorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_excluir_professorActionPerformed

    private void txt_id_professorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_id_professorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_id_professorActionPerformed

    private void rdo_masculino2_professorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdo_masculino2_professorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdo_masculino2_professorActionPerformed

    private void rdo_feminino2_professorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdo_feminino2_professorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdo_feminino2_professorActionPerformed

    private void txt_media_alunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_media_alunoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_media_alunoActionPerformed

    private void txt_faltas_alunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_faltas_alunoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_faltas_alunoActionPerformed

    private void txt_media_aluno2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_media_aluno2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_media_aluno2ActionPerformed

    private void txt_faltas_aluno2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_faltas_aluno2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_faltas_aluno2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CRUD().setVisible(true);
            }
        });
    }
    
    public void limparFormularioAluno(){
        txt_ra_aluno.setText("");
        txt_media_aluno.setText("");
        txt_faltas_aluno.setText("");
        Sexo_aluno.clearSelection();
        cmb_idioma_aluno.setSelectedIndex(0);
    }
    
    public void limparFormularioAluno2(){
        txt_RA_aluno.setText("");
        txt_RA_aluno2.setText("");
        txt_media_aluno2.setText("");
        txt_faltas_aluno2.setText("");
        Sexo_aluno2.clearSelection();
        cmb_idioma_aluno2.setSelectedIndex(0);
    }
    
    public void limparFormularioProfessor(){
        txt_codigo_professor.setText("");
        txt_disciplina_professor.setText("");
        txt_salario_professor.setText("");
        sexo_professor.clearSelection();
        cmb_idioma_professor.setSelectedIndex(0);
    }
    
    public void limparFormularioProfessor2(){
        txt_sexo_professor2.setText("");
        txt_disciplina_professor2.setText("");
        txt_salario_professor2.setText("");
        sexo_professor2.clearSelection();
        cmb_idioma_professor2.setSelectedIndex(0);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Sexo_aluno;
    private javax.swing.ButtonGroup Sexo_aluno2;
    private javax.swing.JButton btn_atualizar_aluno;
    private javax.swing.JButton btn_atualizar_professor;
    private javax.swing.JButton btn_consultar_aluno;
    private javax.swing.JButton btn_consultar_professor;
    private javax.swing.JButton btn_excluir_aluno;
    private javax.swing.JButton btn_excluir_professor;
    private javax.swing.JButton btn_salvar_aluno;
    private javax.swing.JButton btn_salvar_professor;
    private javax.swing.JComboBox<String> cmb_idioma_aluno;
    private javax.swing.JComboBox<String> cmb_idioma_aluno2;
    private javax.swing.JComboBox<String> cmb_idioma_professor;
    private javax.swing.JComboBox<String> cmb_idioma_professor2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbl_faltas_aluno;
    private javax.swing.JLabel lbl_faltas_aluno1;
    private javax.swing.JLabel lbl_form1_aluno;
    private javax.swing.JLabel lbl_form1_professor;
    private javax.swing.JLabel lbl_form2_aluno;
    private javax.swing.JLabel lbl_form2_professor;
    private javax.swing.JLabel lbl_id;
    private javax.swing.JLabel lbl_id2_aluno;
    private javax.swing.JLabel lbl_id2_professor;
    private javax.swing.JLabel lbl_id_professor;
    private javax.swing.JLabel lbl_idioma2_aluno;
    private javax.swing.JLabel lbl_idioma2_professor;
    private javax.swing.JLabel lbl_idioma_aluno;
    private javax.swing.JLabel lbl_idioma_professor;
    private javax.swing.JLabel lbl_media_aluno;
    private javax.swing.JLabel lbl_media_aluno1;
    private javax.swing.JLabel lbl_nome2_professor;
    private javax.swing.JLabel lbl_nome_professor;
    private javax.swing.JLabel lbl_ra_aluno;
    private javax.swing.JLabel lbl_sexo2_aluno;
    private javax.swing.JLabel lbl_sexo2_professor;
    private javax.swing.JLabel lbl_sexo_aluno;
    private javax.swing.JLabel lbl_sexo_professor;
    private javax.swing.JRadioButton rdo_feminino2_aluno;
    private javax.swing.JRadioButton rdo_feminino2_professor;
    private javax.swing.JRadioButton rdo_feminino_aluno;
    private javax.swing.JRadioButton rdo_feminino_professor;
    private javax.swing.JRadioButton rdo_masculino2_aluno;
    private javax.swing.JRadioButton rdo_masculino2_professor;
    private javax.swing.JRadioButton rdo_masculino_aluno;
    private javax.swing.JRadioButton rdo_masculino_professor;
    private javax.swing.ButtonGroup sexo_professor;
    private javax.swing.ButtonGroup sexo_professor2;
    private javax.swing.JTextField txt_ID_professor;
    private javax.swing.JTextField txt_Nome_professor;
    private javax.swing.JTextField txt_RA_aluno;
    private javax.swing.JTextField txt_RA_aluno2;
    private javax.swing.JTextField txt_faltas_aluno;
    private javax.swing.JTextField txt_faltas_aluno2;
    private javax.swing.JTextField txt_id_professor;
    private javax.swing.JTextField txt_media_aluno;
    private javax.swing.JTextField txt_media_aluno2;
    private javax.swing.JTextField txt_nome_professor;
    private javax.swing.JTextField txt_ra_aluno;
    // End of variables declaration//GEN-END:variables
}
