package aula1;


import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 2830482411021
 */
public class JFrame_Aula1 extends javax.swing.JFrame {

    /**
     * Creates new form JFrame_Aula1
     */
    public JFrame_Aula1() {
        initComponents();
    }
    String operador;
    double v1 = 0, v2 = 0, aux;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jButton11 = new javax.swing.JButton();
        btn_click = new javax.swing.JButton();
        btn_n7 = new javax.swing.JButton();
        btn_n8 = new javax.swing.JButton();
        btn_n9 = new javax.swing.JButton();
        btn_n4 = new javax.swing.JButton();
        btn_n5 = new javax.swing.JButton();
        btn_n6 = new javax.swing.JButton();
        btn_n1 = new javax.swing.JButton();
        btn_n2 = new javax.swing.JButton();
        btn_n3 = new javax.swing.JButton();
        btn_n0 = new javax.swing.JButton();
        btn_comma = new javax.swing.JButton();
        btn_negatve = new javax.swing.JButton();
        btn_equal = new javax.swing.JButton();
        btn_mult = new javax.swing.JButton();
        btn_div = new javax.swing.JButton();
        btn_plus = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        btn_blank = new javax.swing.JButton();
        btn_expecificBlank = new javax.swing.JButton();
        txt_calculadora = new javax.swing.JTextField();
        btn_minus = new javax.swing.JButton();
        lbl_valor = new javax.swing.JLabel();

        jToggleButton1.setText("jToggleButton1");

        jButton11.setText("jButton11");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_click.setText("Clque aqui!");
        btn_click.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clickActionPerformed(evt);
            }
        });

        btn_n7.setText("7");
        btn_n7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_n7ActionPerformed(evt);
            }
        });

        btn_n8.setText("8");
        btn_n8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_n8ActionPerformed(evt);
            }
        });

        btn_n9.setText("9");
        btn_n9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_n9ActionPerformed(evt);
            }
        });

        btn_n4.setText("4");
        btn_n4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_n4ActionPerformed(evt);
            }
        });

        btn_n5.setText("5");
        btn_n5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_n5ActionPerformed(evt);
            }
        });

        btn_n6.setText("6");
        btn_n6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_n6ActionPerformed(evt);
            }
        });

        btn_n1.setText("1");
        btn_n1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_n1ActionPerformed(evt);
            }
        });

        btn_n2.setText("2");
        btn_n2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_n2ActionPerformed(evt);
            }
        });

        btn_n3.setText("3");
        btn_n3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_n3ActionPerformed(evt);
            }
        });

        btn_n0.setText("0");
        btn_n0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_n0ActionPerformed(evt);
            }
        });

        btn_comma.setText(",");
        btn_comma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_commaActionPerformed(evt);
            }
        });

        btn_negatve.setText("_");
        btn_negatve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_negatveActionPerformed(evt);
            }
        });

        btn_equal.setText("=");
        btn_equal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_equalActionPerformed(evt);
            }
        });

        btn_mult.setText("x");
        btn_mult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_multActionPerformed(evt);
            }
        });

        btn_div.setText("/");
        btn_div.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_divActionPerformed(evt);
            }
        });

        btn_plus.setText("+");
        btn_plus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_plusActionPerformed(evt);
            }
        });

        btn_delete.setText("<-");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        btn_blank.setText("C");
        btn_blank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_blankActionPerformed(evt);
            }
        });

        btn_expecificBlank.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        btn_expecificBlank.setText("CE");
        btn_expecificBlank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_expecificBlankActionPerformed(evt);
            }
        });

        txt_calculadora.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        btn_minus.setText("-");
        btn_minus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_minusActionPerformed(evt);
            }
        });

        lbl_valor.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_valor.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_n4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_n5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_n6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_mult, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_n1)
                            .addComponent(btn_negatve))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_n0)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_comma)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_equal))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_n2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_n3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_plus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(btn_click)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_n7)
                            .addComponent(btn_minus))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_n8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_n9))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_expecificBlank, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_blank)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_delete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_div, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(2, 2, 2))))
                    .addComponent(txt_calculadora)
                    .addComponent(lbl_valor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btn_minus, btn_n1, btn_n4, btn_n7, btn_negatve});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btn_n0, btn_n2, btn_n5, btn_n8});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btn_comma, btn_n3, btn_n6, btn_n9});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btn_delete, btn_equal});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(lbl_valor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_calculadora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_delete)
                        .addComponent(btn_blank)
                        .addComponent(btn_minus))
                    .addComponent(btn_expecificBlank))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_n7)
                    .addComponent(btn_n8)
                    .addComponent(btn_n9)
                    .addComponent(btn_div))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_n4)
                    .addComponent(btn_n5)
                    .addComponent(btn_n6)
                    .addComponent(btn_mult))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_n1)
                    .addComponent(btn_n2)
                    .addComponent(btn_n3)
                    .addComponent(btn_plus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_n0)
                    .addComponent(btn_comma)
                    .addComponent(btn_negatve)
                    .addComponent(btn_equal))
                .addGap(18, 18, 18)
                .addComponent(btn_click)
                .addContainerGap(94, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btn_minus, btn_n1, btn_n4, btn_n7, btn_negatve});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btn_expecificBlank, btn_n0, btn_n2, btn_n5, btn_n8});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btn_comma, btn_n3, btn_n6, btn_n9});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btn_delete, btn_div, btn_equal, btn_mult, btn_plus});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_clickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clickActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Você ganhou 2 trilhões de reais!!!!!");
    }//GEN-LAST:event_btn_clickActionPerformed

    private void btn_n7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_n7ActionPerformed
        txt_calculadora.setText(txt_calculadora.getText()+"7");
    }//GEN-LAST:event_btn_n7ActionPerformed

    private void btn_n8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_n8ActionPerformed
        txt_calculadora.setText(txt_calculadora.getText()+"8");
    }//GEN-LAST:event_btn_n8ActionPerformed

    private void btn_n9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_n9ActionPerformed
        txt_calculadora.setText(txt_calculadora.getText()+"9");
    }//GEN-LAST:event_btn_n9ActionPerformed

    private void btn_n4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_n4ActionPerformed
        txt_calculadora.setText(txt_calculadora.getText()+"4");
    }//GEN-LAST:event_btn_n4ActionPerformed

    private void btn_n5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_n5ActionPerformed
        txt_calculadora.setText(txt_calculadora.getText()+"5");
    }//GEN-LAST:event_btn_n5ActionPerformed

    private void btn_n6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_n6ActionPerformed
        txt_calculadora.setText(txt_calculadora.getText()+"6");
    }//GEN-LAST:event_btn_n6ActionPerformed

    private void btn_n1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_n1ActionPerformed
        txt_calculadora.setText(txt_calculadora.getText()+"1");
    }//GEN-LAST:event_btn_n1ActionPerformed

    private void btn_n2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_n2ActionPerformed
        txt_calculadora.setText(txt_calculadora.getText()+"2");
    }//GEN-LAST:event_btn_n2ActionPerformed

    private void btn_n3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_n3ActionPerformed
        txt_calculadora.setText(txt_calculadora.getText()+"3");
    }//GEN-LAST:event_btn_n3ActionPerformed

    private void btn_n0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_n0ActionPerformed
        txt_calculadora.setText(txt_calculadora.getText()+"0");
    }//GEN-LAST:event_btn_n0ActionPerformed

    private void btn_commaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_commaActionPerformed
        txt_calculadora.setText(txt_calculadora.getText()+",");
    }//GEN-LAST:event_btn_commaActionPerformed

    private void btn_negatveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_negatveActionPerformed
        lbl_valor.setText(txt_calculadora.getText());
        txt_calculadora.setText("");
    }//GEN-LAST:event_btn_negatveActionPerformed

    private void btn_equalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_equalActionPerformed
        double resultado;
        v2 = Double.parseDouble(txt_calculadora.getText());
        
        System.out.println(v1+"---"+v2);
        
        switch(operador){
            case "*":
                resultado = v1 * v2;
                System.out.println(resultado);
                lbl_valor.setText (v1+"*"+v2+"=");
                txt_calculadora.setText(String.valueOf(resultado));
                break;
                
            case "/":
                resultado = v1 / v2;
                lbl_valor.setText (v1+"/"+v2+"=");
                txt_calculadora.setText(String.valueOf(resultado));
                break;
                
            case "+":
                resultado = v1 + v2;
                lbl_valor.setText (v1+"+"+v2+"=");
                txt_calculadora.setText(String.valueOf(resultado));
                break;
                
            case "-":
                resultado = v1 - v2;
                lbl_valor.setText (v1+"-"+v2+"=");
                txt_calculadora.setText(String.valueOf(resultado));
                break;    
            
        }
    }//GEN-LAST:event_btn_equalActionPerformed

    private void btn_multActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_multActionPerformed
        aux = Double.parseDouble(txt_calculadora.getText());
        v1 = v1 * aux;
        operador = "*";
        
        lbl_valor.setText(v1+"*");
        txt_calculadora.setText("");
        
        
        
    }//GEN-LAST:event_btn_multActionPerformed

    private void btn_divActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_divActionPerformed
        //if(txt_calculadora.getText().matches("")){
            
        //}
        operador = "/";
        
        aux = Double.parseDouble(txt_calculadora.getText());
        v1 = v1 / aux;
            
        lbl_valor.setText(v1+"/");
        txt_calculadora.setText("");
        
        
        
    }//GEN-LAST:event_btn_divActionPerformed

    private void btn_plusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_plusActionPerformed
        //if(txt_calculadora.getText().matches("")){
            
        //}
        aux = Double.parseDouble(txt_calculadora.getText());
        v1 = v1 + aux;
            
        lbl_valor.setText(v1+"+");
        txt_calculadora.setText("");
        
        operador = "+";
        
        
    }//GEN-LAST:event_btn_plusActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void btn_blankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_blankActionPerformed
        txt_calculadora.setText("");
        lbl_valor.setText("");
        v1 = v2 = 0;
    }//GEN-LAST:event_btn_blankActionPerformed

    private void btn_expecificBlankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_expecificBlankActionPerformed
        System.out.println("Almondega");
        txt_calculadora.setText("");
    }//GEN-LAST:event_btn_expecificBlankActionPerformed

    private void btn_minusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_minusActionPerformed
        aux = Double.parseDouble(txt_calculadora.getText());
        v1 = v1 + aux;
        operador = "-";
        
        lbl_valor.setText(v1+"-");
        txt_calculadora.setText("");
    }//GEN-LAST:event_btn_minusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame_Aula1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame_Aula1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame_Aula1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame_Aula1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame_Aula1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_blank;
    private javax.swing.JButton btn_click;
    private javax.swing.JButton btn_comma;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_div;
    private javax.swing.JButton btn_equal;
    private javax.swing.JButton btn_expecificBlank;
    private javax.swing.JButton btn_minus;
    private javax.swing.JButton btn_mult;
    private javax.swing.JButton btn_n0;
    private javax.swing.JButton btn_n1;
    private javax.swing.JButton btn_n2;
    private javax.swing.JButton btn_n3;
    private javax.swing.JButton btn_n4;
    private javax.swing.JButton btn_n5;
    private javax.swing.JButton btn_n6;
    private javax.swing.JButton btn_n7;
    private javax.swing.JButton btn_n8;
    private javax.swing.JButton btn_n9;
    private javax.swing.JButton btn_negatve;
    private javax.swing.JButton btn_plus;
    private javax.swing.JButton jButton11;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel lbl_valor;
    private javax.swing.JTextField txt_calculadora;
    // End of variables declaration//GEN-END:variables
}
