/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ItemNota;

import DAO.ItemNotaDAO;
import DAO.NotaDAO;
import DAO.ProdutoDAO;
import Nota.Nota;
import Produto.Produto;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author fan25
 */
public class ItemNotaCadastrar extends javax.swing.JFrame {

    /**
     * Creates new form ItemNotaCadastrar
     */
    public ItemNotaCadastrar() {
        initComponents();
        preencherComboProduto();
        preencherComboNota();
    }
    
    public void preencherComboProduto(){
        ProdutoDAO produtoDAO = new ProdutoDAO();
        List<Produto> listaProdutos = produtoDAO.getProdutos();
        cmb_produtos.addItem("");
        for(Produto produto : listaProdutos){
            cmb_produtos.addItem(produto);
        }
    }
    
    public void preencherComboNota(){
        NotaDAO notaDAO = new NotaDAO();
        List<Nota> listaNotas = notaDAO.getNotas();
        cmb_notas.addItem("");
        for(Nota nota : listaNotas){
            cmb_notas.addItem(nota);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmb_notas = new javax.swing.JComboBox();
        lbl_preco = new javax.swing.JLabel();
        lbl_qtdEstoque = new javax.swing.JLabel();
        lbl_Cadastro = new javax.swing.JLabel();
        btn_cadastrar = new javax.swing.JButton();
        btn_limpar = new javax.swing.JButton();
        btn_listarNotas = new javax.swing.JButton();
        cmb_produtos = new javax.swing.JComboBox();
        lbl_quantidade = new javax.swing.JLabel();
        txt_quantidade = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lbl_preco.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbl_preco.setText("Produto:");

        lbl_qtdEstoque.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbl_qtdEstoque.setText("Nota Fiscal:");

        lbl_Cadastro.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lbl_Cadastro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Cadastro.setText("Cadastro dos Itens das Notas");

        btn_cadastrar.setText("Cadastrar");
        btn_cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadastrarActionPerformed(evt);
            }
        });

        btn_limpar.setText("Limpar");
        btn_limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limparActionPerformed(evt);
            }
        });

        btn_listarNotas.setText("Listar Itens das Notas");
        btn_listarNotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_listarNotasActionPerformed(evt);
            }
        });

        lbl_quantidade.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbl_quantidade.setText("Quantidade:");

        txt_quantidade.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(btn_limpar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addComponent(btn_cadastrar)
                .addGap(74, 74, 74))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_Cadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_qtdEstoque)
                            .addComponent(lbl_preco))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmb_produtos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmb_notas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_quantidade)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_quantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_listarNotas)
                .addGap(125, 125, 125))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_Cadastro)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_quantidade)
                    .addComponent(txt_quantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_preco)
                    .addComponent(cmb_produtos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_qtdEstoque)
                    .addComponent(cmb_notas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_limpar)
                    .addComponent(btn_cadastrar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_listarNotas)
                .addContainerGap(100, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastrarActionPerformed
        if(cmb_produtos.getSelectedItem().equals("") || cmb_notas.getSelectedItem().equals("") || txt_quantidade.getText().equals("")){
            JOptionPane.showMessageDialog(
                null,
                "É necessário que todos os campos estejam preenchidos!!",
                "Preencha todos os campos!!",
                JOptionPane.OK_OPTION
            );
        } else{
            ItemNota itemNota = new ItemNota();
            Nota nota = (Nota) cmb_notas.getSelectedItem();
            Produto produto = (Produto) cmb_produtos.getSelectedItem();
            
            itemNota.setQuantidade(Integer.parseInt(txt_quantidade.getText()));
            itemNota.setNta_Codigo(nota);
            itemNota.setPro_Codigo(produto);
            

            ItemNotaDAO itemnotaDAO = new ItemNotaDAO();
            itemnotaDAO.cadastrar(itemNota);

            limparFormulario();
        }
    }//GEN-LAST:event_btn_cadastrarActionPerformed

    private void btn_limparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limparActionPerformed
        limparFormulario();
    }//GEN-LAST:event_btn_limparActionPerformed

    private void btn_listarNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_listarNotasActionPerformed
        ItemNotaListar listItemNota = new ItemNotaListar();
        listItemNota.setVisible(true);
    }//GEN-LAST:event_btn_listarNotasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ItemNotaCadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ItemNotaCadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ItemNotaCadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ItemNotaCadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ItemNotaCadastrar().setVisible(true);
            }
        });
    }
    
    public void limparFormulario(){
        cmb_produtos.setSelectedIndex(0);
        cmb_notas.setSelectedIndex(0);
        txt_quantidade.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cadastrar;
    private javax.swing.JButton btn_limpar;
    private javax.swing.JButton btn_listarNotas;
    private javax.swing.JComboBox cmb_notas;
    private javax.swing.JComboBox cmb_produtos;
    private javax.swing.JLabel lbl_Cadastro;
    private javax.swing.JLabel lbl_preco;
    private javax.swing.JLabel lbl_qtdEstoque;
    private javax.swing.JLabel lbl_quantidade;
    private javax.swing.JTextField txt_quantidade;
    // End of variables declaration//GEN-END:variables
}
