/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Nota;

import Cliente.Cliente;
import DAO.ClienteDAO;
import DAO.FornecedorDAO;
import DAO.NotaDAO;
import Fornecedor.Fornecedor;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author fan25
 */
public class NotaCadastrar extends javax.swing.JFrame {

    /**
     * Creates new form NotaCadastrar
     */
    public NotaCadastrar() {
        initComponents();
        preencherComboCliente();
        preencherComboFornecedor();
    }
    
    public void preencherComboCliente(){
        ClienteDAO clienteDAO = new ClienteDAO();
        List<Cliente> listaClientes = clienteDAO.getClientes();
        cmb_cliente.addItem("");
        for(Cliente cliente : listaClientes){
            cmb_cliente.addItem(cliente);
        }
    }
    
    public void preencherComboFornecedor(){
        FornecedorDAO fornecedorDAO = new FornecedorDAO();
        List<Fornecedor> listaFornecedor = fornecedorDAO.getFornecedores();
        cmb_fornecedor.addItem("");
        for(Fornecedor fornecedor : listaFornecedor){
            cmb_fornecedor.addItem(fornecedor);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TipoNota = new javax.swing.ButtonGroup();
        lbl_preco = new javax.swing.JLabel();
        lbl_qtdEstoque = new javax.swing.JLabel();
        lbl_desc = new javax.swing.JLabel();
        lbl_Cadastro = new javax.swing.JLabel();
        btn_cadastrar = new javax.swing.JButton();
        btn_limpar = new javax.swing.JButton();
        btn_listarNotas = new javax.swing.JButton();
        cmb_cliente = new javax.swing.JComboBox();
        cmb_fornecedor = new javax.swing.JComboBox();
        rdo_entrada = new javax.swing.JRadioButton();
        rdo_saida = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lbl_preco.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbl_preco.setText("Cliente: ");

        lbl_qtdEstoque.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbl_qtdEstoque.setText("Fornecedor:");

        lbl_desc.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbl_desc.setText("Tipo da Nota:");

        lbl_Cadastro.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lbl_Cadastro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Cadastro.setText("Cadastro de Notas");

        btn_cadastrar.setText("Cadastrar");
        btn_cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadastrarActionPerformed(evt);
            }
        });

        btn_limpar.setText("Limpar");
        btn_limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limparActionPerformed(evt);
            }
        });

        btn_listarNotas.setText("Listar Notas");
        btn_listarNotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_listarNotasActionPerformed(evt);
            }
        });

        TipoNota.add(rdo_entrada);
        rdo_entrada.setText("Entrada");

        TipoNota.add(rdo_saida);
        rdo_saida.setText("Saída");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(btn_limpar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addComponent(btn_cadastrar)
                .addGap(74, 74, 74))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_listarNotas)
                .addGap(150, 150, 150))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_Cadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_desc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rdo_entrada)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rdo_saida))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_qtdEstoque)
                            .addComponent(lbl_preco))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmb_cliente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmb_fornecedor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_Cadastro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_preco)
                    .addComponent(cmb_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_qtdEstoque)
                    .addComponent(cmb_fornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_desc)
                    .addComponent(rdo_saida)
                    .addComponent(rdo_entrada))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_limpar)
                    .addComponent(btn_cadastrar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_listarNotas)
                .addContainerGap(143, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastrarActionPerformed
        int tipo = -1;
        
        if(rdo_entrada.isSelected()){
            tipo = 1;
        } else if(rdo_saida.isSelected()){
            tipo = 2;
        }
        
        if(tipo == -1){
            JOptionPane.showMessageDialog(null, "É necessario definir o tipo da Nota a ser Inserida!!", "Tipo de Nota Não Selecionado!", JOptionPane.OK_OPTION);
        } else if(!cmb_cliente.getSelectedItem().equals("") && tipo == 1 || !cmb_fornecedor.getSelectedItem().equals("") && tipo == 2 || cmb_cliente.getSelectedItem().equals("") && cmb_fornecedor.getSelectedItem().equals("")){
            JOptionPane.showMessageDialog(
                    null,
                    "É necessário inserir o Usuario respectivo ao tipo de Nota desejado!"
                    + "\n  -Se for 'Entrada', insira um 'Fornecedor'"
                    + "\n  -Se for 'Saída', insira um 'Cliente'", 
                    "Tipo de Usuario Não é Compativel com a Nota!",
                    JOptionPane.OK_OPTION
            );
        } else{
            Nota nota = new Nota();
            if(cmb_cliente.getSelectedItem().equals("")){
                Fornecedor fornecedor = (Fornecedor) cmb_fornecedor.getSelectedItem();
                nota.setFor_Codigo(fornecedor);
            } else{
                Cliente cli = (Cliente) cmb_cliente.getSelectedItem();
                nota.setCli_Codigo(cli);
            }
            nota.setTip_Codigo(tipo);

            NotaDAO notaDAO = new NotaDAO();
            notaDAO.cadastrar(nota);

            limparFormulario();
        }
    }//GEN-LAST:event_btn_cadastrarActionPerformed

    private void btn_limparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limparActionPerformed
        limparFormulario();
    }//GEN-LAST:event_btn_limparActionPerformed

    private void btn_listarNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_listarNotasActionPerformed
        NotaListar listNota = new NotaListar();
        listNota.setVisible(true);

    }//GEN-LAST:event_btn_listarNotasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NotaCadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NotaCadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NotaCadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NotaCadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NotaCadastrar().setVisible(true);
            }
        });
    }
    
    public void limparFormulario(){
        cmb_cliente.setSelectedIndex(0);
        cmb_fornecedor.setSelectedIndex(0);
        TipoNota.clearSelection();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup TipoNota;
    private javax.swing.JButton btn_cadastrar;
    private javax.swing.JButton btn_limpar;
    private javax.swing.JButton btn_listarNotas;
    private javax.swing.JComboBox cmb_cliente;
    private javax.swing.JComboBox cmb_fornecedor;
    private javax.swing.JLabel lbl_Cadastro;
    private javax.swing.JLabel lbl_desc;
    private javax.swing.JLabel lbl_preco;
    private javax.swing.JLabel lbl_qtdEstoque;
    private javax.swing.JRadioButton rdo_entrada;
    private javax.swing.JRadioButton rdo_saida;
    // End of variables declaration//GEN-END:variables
}
